Vagrant.configure("2") do |config|

  # Ubuntu
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "webfusion-vm"

  # WordPress
  config.vm.network "forwarded_port",
    guest: 8080,
    host:  8080,
    host_ip: "127.0.0.1"

  # Recursos
  config.vm.provider "virtualbox" do |vb|
    vb.name   = "WebFusion Digital VM"
    vb.memory = "2048"
    vb.cpus   = 2
  end

  # Aprovisionamiento
  config.vm.provision "shell", privileged: true, inline: <<-SHELL

    # 1. Actualizar sistema

    apt-get update -qq

    # 2. Instalar dependencias
    apt-get install -y -qq ca-certificates curl gnupg lsb-release git

    # 3. Instalar Docker

    if ! command -v docker &> /dev/null; then
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
            | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg

        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
          https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
          | tee /etc/apt/sources.list.d/docker.list > /dev/null

        apt-get update -qq
        apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
            docker-buildx-plugin docker-compose-plugin

        systemctl enable docker
        systemctl start docker
        usermod -aG docker vagrant
        echo "Docker instalado correctamente."
    else
        echo "Docker ya estaba instalado."
    fi

    # 4. Desplegar con Docker Compose
    cd /vagrant
    docker compose down git-sync 2>/dev/null || true
    docker compose up -d db wordpress
    sleep 10
    docker compose run --rm git-sync

    echo ""
    echo "=============================================="
    echo "  WordPress --> http://localhost:8080"
  SHELL
end